### ISSUE TITLE
bash: command not found

### ISSUE THREAD

**Issue by kablaziken** [B0ney/xmodits#16]
I put an .xm into build-multi.sh but my .xm file is 1k mb, could that be the source of it?

**Comment by B0ney** [comment]
"build-multi.sh" compiles the program, so it's not intended to be used by the end user.

I've made the file size limit **64MiB**, so I would be very surprised if a tracker ever reached that size. 

If you haven't already, download the binary for [linux](https://github.com/B0ney/xmodits/releases/download/0.9.5/xmodits-linux.zip) or [windows](https://github.com/B0ney/xmodits/releases/download/0.9.5/xmodits-windows.zip) ([release page](https://github.com/B0ney/xmodits/releases/tag/0.9.5)).

Extract the zip file.

Assuming you're using Linux:

Open the terminal, and ```cd``` to the destination folder:

```cd ~/Downloads/xmodits-linux/``` (assuming the extracted data is at ```~/Downloads/xmodits-linux/```)

Then run the program:

```./xmodits your_tracker.xm```

Where "your_tracker.xm" is a valid path to the tracker.

If successful, xmodits will create a new folder in the same directory called: ```your_tracker_xm``` and place the ripped the samples there :)
