### ISSUE TITLE
bash: cargo: command not found

### ISSUE THREAD

**Issue by kablaziken** [B0ney/xmodits#18]
after finding a track that is smaller, even when uncompressed, it now flashes this message, sometimes not even showing it. i use git so maybe thats the problem but idk

**Comment by kablaziken** [comment]
the first .xm file i tried to rip the samples out of was ~300kb, and the second one i tried was ~60kb. both didnt work, showing that message.

**Comment by kablaziken** [comment]
> the first .xm file i tried to rip the samples out of was ~600kb, and the second one i tried was ~60kb. both didnt work, showing that message.

even a ~110kb .it file didnt work

**Comment by B0ney** [comment]
Can you show me what you typed in the terminal?

**Comment by B0ney** [comment]
"bash: cargo: command not found" - To me, it seems that you're still trying to use "build-multi.sh", can you follow my suggestion from https://github.com/B0ney/xmodits/issues/16#issuecomment-1265801524 and tell me if you're still having issues?

**Comment by kablaziken** [comment]
yeah it did. wow, honestly how did i even not know where the binary is lol

**Comment by B0ney** [comment]
That's good to hear
